---
# Main task install common packages
- name: Defaut package manager
  debug: var=ansible_pkg_mgr

- name: Start install common packages  on selected OS
  include_tasks: "{{ ansible_facts['distribution'] }}.yml"

- name: Start install common on MacOs (Homebrew)
  include_tasks: MacOs.yml
  when: ansible_pkg_mgr == "homebrew"
